### ISSUE TITLE
Não sei se é uma falha?

### ISSUE THREAD

**Issue by s3mPr1linux** [loiane/curso-java-basico#13]
Olá Loiane, primeiro gostaria de te paabenizar pelos cursos gratuitos , que são de muita qualidade, porém quando estou assistindo as aulas pelo seu portal toda hora o site desloga e interrompe o video.
Ai temos que relogar para voltar a assistir, e eu acabo indo pro youtube.

Não sei se e algum problema do meu navegador ou do portal.

**Comment by rafaelantunesjf** [comment]
Sim, isso está acontecendo comigo também. Acredito a sessão no https://loiane.training/ deveria ter um tempo maior.


Saudações;

**Comment by loiane** [comment]
oie, obrigada por abrir a issue. A sessão é controlada pelo firebase, até o momento não achei o fix para esse problema. O que recomendo como workaround é assistir o vídeo pelo youtube e marcar no portal até que a API de sessão exponha algo para configurar o limite de tempo.

**Comment by eugeniobr25** [comment]
Eu to assistindo todos os videos pela plataforma, so os exercícios que fico assistindo pelo youtube pra não precisar ficar relogando.

**Comment by s3mPr1linux** [comment]
certo obrigado.
