### ISSUE TITLE
Dúvida!

### ISSUE THREAD

**Issue by EnzoAlexsander** [loiane/curso-java-basico#15]
Olá Loiane
Eu estou fazendo um curso de java do canal DevDojo no Youtube
Estou gostando muito, porém sinto falta de exercícios.
Amigos meus ja me recomendaram o seu curso por ser um conteúdo excelente e com bastante prática
Porém seu curso é de 2013 e o curso de Java do DevDojo é de 2016 e eu ja passei da metade do curso
Com a experiência que você tem, você acha que me atrapalharia fazer o seu curso por ser um java inferior agora que ja comecei aprendendo de uma versão do java mais avançada?

**Comment by luisangelorjr** [comment]
Opa @EnzoAlexsander!
O java que é utilizado é a versao 7, [conforme vídeo](https://youtu.be/ddhH97IPrFY), e pelo que vi na época que comecei, não tive problema algum de adaptação para o Java 8 ou 11 (que são os mais utilizados hoje em dia segundo [uma](https://www.jetbrains.com/lp/devecosystem-2019/java/#:~:text=Although%20Java%2010%20and%2011,still%20the%20most%20used%20version.) ou [outra pesquisa](https://snyk.io/blog/developers-dont-want-to-leave-java-8-as-64-hold-firm-on-their-preferred-release/) por serem [LTS](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)) ou até do Java 14 (não vi muito).

Entendo que para quem está iniciando não irá topar com problemas ou necessidades que só as JDKs mais atuais possam auxiliar, [vide exemplo de artigo falando para sair do Java 8](https://dev.to/awwsmm/20-reasons-to-move-on-from-java-8-1dio).

Atente-se para a base mostrada no curso que ela se mantém até hoje 🥇 
Abs. É noiz!
#perifaCode

**Comment by EnzoAlexsander** [comment]
Valeu amigo!
