### ISSUE TITLE
Exercícios de fixação

### ISSUE THREAD

**Issue by andremeiras** [loiane/curso-java-basico#16]
Olá Loiane e comunidade, tudo certo?

Estive estudando o curso Java Básico e já até terminei ele. Atualmente dei uma pausa pois estou participando de outros dois projetos um pouco mais avançados mas assim que der uma folga lá quero voltar para o de Java Intermediário da Loiane também pois são muito bons e conhecimento, mesmo que básico é sempre bom estar revisando pra manter fresco na memória né.

Obrigado Loiane pela sua contribuição. ;)

Só gostaria de fazer um pedido pois não encontrei e desculpe se este não é o lugar certo pra pedir isso.

Gostaria que disponibilizasse se possível as listas de exercícios que utilizou em ambos os cursos, e caso já tenha, por favor, poderia me informar onde posso encontrar?

Mais uma vez, agradeço pela sua contribuição.

Forte abraço à todos!

**Comment by avpinheiro** [comment]
Oi André,
Também não tinha achado a lista de execícios, mas depois de muito procurar consegui achar, aí está o link: https://www.slideshare.net/loianeg/curso-java-bsico-exerccios-aulas-11-12-13.

Encontrei no site da nossa querida Loiane várias outras informações que poderão ser úteis, navegue nos posts até a página 5/45:
http://loiane.com/

Abraço.

**Comment by andremeiras** [comment]
> Oi André,
> Também não tinha achado a lista de execícios, mas depois de muito procurar consegui achar, aí está o link: https://www.slideshare.net/loianeg/curso-java-bsico-exerccios-aulas-11-12-13.
> 
> Encontrei no site da nossa querida Loiane várias outras informações que poderão ser úteis, navegue nos posts até a página 5/45:
> http://loiane.com/
> 
> Abraço.

Ótimo @avpinheiro. 

Eu ainda não havia navegado pelo blog. Realmente nos posts tem os links. 

Muito obrigado!

Abs.
