### ISSUE TITLE
Dúvida, Git e GitHub

### ISSUE THREAD

**Issue by ChristoferFernandes** [loiane/curso-java-basico#24]
Olá, boa noite! Tudo bom Loiane?

O motivo de eu vir aqui pedir ajuda é a seguinte, eu estou tentando utilizar o git e github para publicar todos os exercícios e tudo mais que estou fazendo no curso de java básico contigo, mas estou tendo um problema referente a salvar os arquivos, geralmente está dando problema porque como estou tentando utilizar a IDE Intellij, não está reconhecendo e todos os meus arquivos .java não reconhece não fica como uma classe, só fica como um arquivo. Como se fosse um txt

![image](https://user-images.githubusercontent.com/67238384/193949496-ee4c19a9-a375-456d-9b41-aa74783d0095.png)

Você consegue me ajudar?

**Comment by jhowilbur** [comment]
Olá, você precisa configurar a IDE para identificar cada pasta

Voce configurou alguma versão Java pro intellij ou ele perguntou algo do tipo quando você inicializou?

**Comment by ChristoferFernandes** [comment]
@jhowilbur , no intellij eu deixo configurado com o java jdk 11, que é o que eu uso.
![image](https://user-images.githubusercontent.com/67238384/194171704-d1be7ed3-236f-4c84-ae01-c7bb1d8a4855.png)

e está configurado corretamente, mas o meu problema está sendo o seguinte, ele não está reconhecendo a nova pasta que criei como uma package, ou o arquivo.java como classe.
![image](https://user-images.githubusercontent.com/67238384/194171848-4cd289a2-59be-4221-9e02-d6416a4639a9.png)

**Comment by ChristoferFernandes** [comment]
Gente, passando aqui apenas para avisar que eu conseguir resolver, eu mudei o diretório da pasta no arquivo iml, e deu certo eu descobri que posso adicionar ou remover ao meu gosto.
segue o print.

![image](https://user-images.githubusercontent.com/67238384/194193127-414ff11c-3f6f-4340-8cee-3ed04e0b2bf7.png)
